### ISSUE TITLE
Runnel struct aliasing feature breaks ehcache 3 codecs

### ISSUE THREAD

**Issue by lorban** [Terracotta-OSS/terracotta-platform#199]
See: https://github.com/ehcache/ehcache3/issues/1650

The ehcache integration tests fail with the following error when using the latest runnel that contains the struct aliasing feature:

```
<snipped>
Caused by: org.terracotta.entity.MessageCodecException: Runtime exception in deserializer
 	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:291)
 	... 11 more
 Caused by: java.lang.IllegalArgumentException: No such field : elements
 	at org.terracotta.runnel.metadata.FieldSearcher.findField(FieldSearcher.java:40)
 	at org.terracotta.runnel.encoding.StructEncoder.structs(StructEncoder.java:222)
 	at org.ehcache.clustered.common.internal.messages.ChainCodec.encode(ChainCodec.java:55)
 	at org.ehcache.clustered.common.internal.messages.ResponseCodec$1.encode(ResponseCodec.java:118)
 	at org.terracotta.runnel.encoding.StructEncoder.struct(StructEncoder.java:130)
 	at org.ehcache.clustered.common.internal.messages.ResponseCodec.encode(ResponseCodec.java:113)
 	at org.ehcache.clustered.common.internal.messages.EhcacheCodec.encodeResponse(EhcacheCodec.java:112)
 	at org.ehcache.clustered.server.internal.messages.EhcacheServerCodec.encodeResponse(EhcacheServerCodec.java:86)
 	at org.ehcache.clustered.server.internal.messages.EhcacheServerCodec.encodeResponse(EhcacheServerCodec.java:37)
 	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$performAction$78(ManagedEntityImpl.java:622)
 	at com.tc.objectserver.entity.ManagedEntityImpl$$Lambda$32/1717492671.run(Unknown Source)
 	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:286)
 	... 11 more
```

**Comment by anthonydahanne** [comment]
closed with https://github.com/Terracotta-OSS/terracotta-platform/pull/200
